package electiva;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : App.java
//  @ Date : 26/02/2015
//  @ Author : 
//
//

public class App1 implements Aplicacion{
	private String id;
	private String nombre;
	private Boolean estado;
	public Flujo procesarFlujos(Flujo f) {
            //TODO: agregar proceso
            return f;
	}
}
